#!/bin/sh -p
set -eu
unset IFS
CDPATH=
export CDPATH

# Public entry point for the release supervisor. Use only shell builtins until
# env -i replaces the hostile caller environment; no Perl, Node, dynamic-
# language loader, proxy, credential, or shell-startup hook crosses this line.
physical_cwd=$(command pwd -P) || exit 126
case $0 in
  /*) launcher_path=$0 ;;
  *) launcher_path=$physical_cwd/$0 ;;
esac
launcher_parent=${launcher_path%/*}
SCRIPT_DIR=$(CDPATH= command cd -P -- "$launcher_parent" 2>/dev/null && command pwd -P) || {
  echo "The watchdog clean-environment launcher could not resolve its source directory." >&2
  exit 126
}
case $SCRIPT_DIR in /*) ;; *) exit 126 ;; esac
[ -d "$SCRIPT_DIR" ] && [ ! -L "$SCRIPT_DIR" ] && [ ! -L "$launcher_path" ] \
  || {
  echo "The watchdog clean-environment launcher could not attest its runtime paths." >&2
  exit 126
}

# Forwarded controls used to be serialized as literal `NAME=value` arguments
# to the clean bootstrap. That made a signing password, Harness auth token, and
# root capability visible to every same-user process that could read a broad
# process listing. A shell-created, owner-only, already-unlinked here-document
# descriptor now carries the bounded record. No forwarded value enters a child
# argv, no pathname can be raced, and the descriptor is consumed exactly once.
append_forwarded_control() {
  forwarded_name=$1
  eval "forwarded_present=\${$forwarded_name+x}"
  [ "$forwarded_present" = x ] || return 0
  eval "forwarded_value=\${$forwarded_name}"
  case $forwarded_value in *'
'*|*''*) return 126 ;; esac
}
for forwarded_name in \
  CI GITHUB_ACTIONS DEVELOPER_DIR \
  FULMAR_CI_REQUIRE_CURRENT_CANDIDATE_TESTS FULMAR_CLEAN_RELEASE_MODE \
  FULMAR_INTERNAL_WATCHDOG_DEPTH FULMAR_RELEASE_EVIDENCE_TEST_KILL_AT \
  FULMAR_RELEASE_EVIDENCE_TEST_ONLY FULMAR_RELEASE_EVIDENCE_TEST_VERIFIER \
  FULMAR_ROOT_WATCHDOG_CAPABILITY_V1 FULMAR_ROOT_WATCHDOG_FD_V1 \
  FULMAR_ROOT_WATCHDOG_NONCE_V1 FULMAR_ROOT_WATCHDOG_PGID_V1 \
  FULMAR_ROOT_WATCHDOG_PID_V1 FULMAR_SWIFT_BUILD_JOBS \
  FULMAR_SWIFT_WATCHDOG_EMERGENCY_RSS_BYTES FULMAR_SWIFT_WATCHDOG_RSS_BYTES \
  FULMAR_SWIFT_WATCHDOG_RSS_GRACE_SECONDS FULMAR_SWIFT_WATCHDOG_SECONDS \
  FULMAR_THERMAL_RECOVERY_TEST_PROBE_V1 FULMAR_AUTH_TOKEN_FD_V1 \
  FULMAR_SIGNING_SECRET_FD_V1 LOCAL_HARNESS_ALLOW_PRIVATE_ROOT \
  LOCAL_HARNESS_AUTH_TOKEN LOCAL_HARNESS_CANARY_STATE \
  LOCAL_HARNESS_CLEAN_RELEASE_ENVIRONMENT LOCAL_HARNESS_CLONED_DSH_SOURCE \
  LOCAL_HARNESS_DSH_DIR LOCAL_HARNESS_NODE_BIN LOCAL_HARNESS_NOTARY_PROFILE \
  LOCAL_HARNESS_READONLY_ROOTS LOCAL_HARNESS_REQUIRE_NONEMPTY_CLONE \
  LOCAL_HARNESS_REQUIRE_STABLE_SIGNING LOCAL_HARNESS_SIGNING_KEYCHAIN \
  LOCAL_HARNESS_SIGNING_KEYCHAIN_PASSWORD LOCAL_HARNESS_SIGN_IDENTITY \
  LOCAL_HARNESS_SIGN_TIMESTAMP LOCAL_HARNESS_JS_TEST_ISOLATION_ROOT \
  LOCAL_HARNESS_TEST_APP_PATH LOCAL_HARNESS_TEST_NODE \
  LOCAL_HARNESS_UPDATE_ARCHIVE_TEST_PATH REQUESTED_BUILD_JOBS \
  REQUESTED_PARALLELISM; do
  append_forwarded_control "$forwarded_name" || exit 126
done
unset forwarded_name forwarded_present forwarded_value
umask 077
exec 9<<FULMAR_WATCHDOG_BOOTSTRAP_RECORD_V2
FULMAR_WATCHDOG_BOOTSTRAP_V2
CI
${CI+x}
${CI-}
GITHUB_ACTIONS
${GITHUB_ACTIONS+x}
${GITHUB_ACTIONS-}
DEVELOPER_DIR
${DEVELOPER_DIR+x}
${DEVELOPER_DIR-}
FULMAR_CI_REQUIRE_CURRENT_CANDIDATE_TESTS
${FULMAR_CI_REQUIRE_CURRENT_CANDIDATE_TESTS+x}
${FULMAR_CI_REQUIRE_CURRENT_CANDIDATE_TESTS-}
FULMAR_CLEAN_RELEASE_MODE
${FULMAR_CLEAN_RELEASE_MODE+x}
${FULMAR_CLEAN_RELEASE_MODE-}
FULMAR_INTERNAL_WATCHDOG_DEPTH
${FULMAR_INTERNAL_WATCHDOG_DEPTH+x}
${FULMAR_INTERNAL_WATCHDOG_DEPTH-}
FULMAR_RELEASE_EVIDENCE_TEST_KILL_AT
${FULMAR_RELEASE_EVIDENCE_TEST_KILL_AT+x}
${FULMAR_RELEASE_EVIDENCE_TEST_KILL_AT-}
FULMAR_RELEASE_EVIDENCE_TEST_ONLY
${FULMAR_RELEASE_EVIDENCE_TEST_ONLY+x}
${FULMAR_RELEASE_EVIDENCE_TEST_ONLY-}
FULMAR_RELEASE_EVIDENCE_TEST_VERIFIER
${FULMAR_RELEASE_EVIDENCE_TEST_VERIFIER+x}
${FULMAR_RELEASE_EVIDENCE_TEST_VERIFIER-}
FULMAR_ROOT_WATCHDOG_CAPABILITY_V1
${FULMAR_ROOT_WATCHDOG_CAPABILITY_V1+x}
${FULMAR_ROOT_WATCHDOG_CAPABILITY_V1-}
FULMAR_ROOT_WATCHDOG_FD_V1
${FULMAR_ROOT_WATCHDOG_FD_V1+x}
${FULMAR_ROOT_WATCHDOG_FD_V1-}
FULMAR_ROOT_WATCHDOG_NONCE_V1
${FULMAR_ROOT_WATCHDOG_NONCE_V1+x}
${FULMAR_ROOT_WATCHDOG_NONCE_V1-}
FULMAR_ROOT_WATCHDOG_PGID_V1
${FULMAR_ROOT_WATCHDOG_PGID_V1+x}
${FULMAR_ROOT_WATCHDOG_PGID_V1-}
FULMAR_ROOT_WATCHDOG_PID_V1
${FULMAR_ROOT_WATCHDOG_PID_V1+x}
${FULMAR_ROOT_WATCHDOG_PID_V1-}
FULMAR_SWIFT_BUILD_JOBS
${FULMAR_SWIFT_BUILD_JOBS+x}
${FULMAR_SWIFT_BUILD_JOBS-}
FULMAR_SWIFT_WATCHDOG_EMERGENCY_RSS_BYTES
${FULMAR_SWIFT_WATCHDOG_EMERGENCY_RSS_BYTES+x}
${FULMAR_SWIFT_WATCHDOG_EMERGENCY_RSS_BYTES-}
FULMAR_SWIFT_WATCHDOG_RSS_BYTES
${FULMAR_SWIFT_WATCHDOG_RSS_BYTES+x}
${FULMAR_SWIFT_WATCHDOG_RSS_BYTES-}
FULMAR_SWIFT_WATCHDOG_RSS_GRACE_SECONDS
${FULMAR_SWIFT_WATCHDOG_RSS_GRACE_SECONDS+x}
${FULMAR_SWIFT_WATCHDOG_RSS_GRACE_SECONDS-}
FULMAR_SWIFT_WATCHDOG_SECONDS
${FULMAR_SWIFT_WATCHDOG_SECONDS+x}
${FULMAR_SWIFT_WATCHDOG_SECONDS-}
FULMAR_THERMAL_RECOVERY_TEST_PROBE_V1
${FULMAR_THERMAL_RECOVERY_TEST_PROBE_V1+x}
${FULMAR_THERMAL_RECOVERY_TEST_PROBE_V1-}
FULMAR_AUTH_TOKEN_FD_V1
${FULMAR_AUTH_TOKEN_FD_V1+x}
${FULMAR_AUTH_TOKEN_FD_V1-}
FULMAR_SIGNING_SECRET_FD_V1
${FULMAR_SIGNING_SECRET_FD_V1+x}
${FULMAR_SIGNING_SECRET_FD_V1-}
LOCAL_HARNESS_ALLOW_PRIVATE_ROOT
${LOCAL_HARNESS_ALLOW_PRIVATE_ROOT+x}
${LOCAL_HARNESS_ALLOW_PRIVATE_ROOT-}
LOCAL_HARNESS_AUTH_TOKEN
${LOCAL_HARNESS_AUTH_TOKEN+x}
${LOCAL_HARNESS_AUTH_TOKEN-}
LOCAL_HARNESS_CANARY_STATE
${LOCAL_HARNESS_CANARY_STATE+x}
${LOCAL_HARNESS_CANARY_STATE-}
LOCAL_HARNESS_CLEAN_RELEASE_ENVIRONMENT
${LOCAL_HARNESS_CLEAN_RELEASE_ENVIRONMENT+x}
${LOCAL_HARNESS_CLEAN_RELEASE_ENVIRONMENT-}
LOCAL_HARNESS_CLONED_DSH_SOURCE
${LOCAL_HARNESS_CLONED_DSH_SOURCE+x}
${LOCAL_HARNESS_CLONED_DSH_SOURCE-}
LOCAL_HARNESS_DSH_DIR
${LOCAL_HARNESS_DSH_DIR+x}
${LOCAL_HARNESS_DSH_DIR-}
LOCAL_HARNESS_NODE_BIN
${LOCAL_HARNESS_NODE_BIN+x}
${LOCAL_HARNESS_NODE_BIN-}
LOCAL_HARNESS_NOTARY_PROFILE
${LOCAL_HARNESS_NOTARY_PROFILE+x}
${LOCAL_HARNESS_NOTARY_PROFILE-}
LOCAL_HARNESS_READONLY_ROOTS
${LOCAL_HARNESS_READONLY_ROOTS+x}
${LOCAL_HARNESS_READONLY_ROOTS-}
LOCAL_HARNESS_REQUIRE_NONEMPTY_CLONE
${LOCAL_HARNESS_REQUIRE_NONEMPTY_CLONE+x}
${LOCAL_HARNESS_REQUIRE_NONEMPTY_CLONE-}
LOCAL_HARNESS_REQUIRE_STABLE_SIGNING
${LOCAL_HARNESS_REQUIRE_STABLE_SIGNING+x}
${LOCAL_HARNESS_REQUIRE_STABLE_SIGNING-}
LOCAL_HARNESS_SIGNING_KEYCHAIN
${LOCAL_HARNESS_SIGNING_KEYCHAIN+x}
${LOCAL_HARNESS_SIGNING_KEYCHAIN-}
LOCAL_HARNESS_SIGNING_KEYCHAIN_PASSWORD
${LOCAL_HARNESS_SIGNING_KEYCHAIN_PASSWORD+x}
${LOCAL_HARNESS_SIGNING_KEYCHAIN_PASSWORD-}
LOCAL_HARNESS_SIGN_IDENTITY
${LOCAL_HARNESS_SIGN_IDENTITY+x}
${LOCAL_HARNESS_SIGN_IDENTITY-}
LOCAL_HARNESS_SIGN_TIMESTAMP
${LOCAL_HARNESS_SIGN_TIMESTAMP+x}
${LOCAL_HARNESS_SIGN_TIMESTAMP-}
LOCAL_HARNESS_JS_TEST_ISOLATION_ROOT
${LOCAL_HARNESS_JS_TEST_ISOLATION_ROOT+x}
${LOCAL_HARNESS_JS_TEST_ISOLATION_ROOT-}
LOCAL_HARNESS_TEST_APP_PATH
${LOCAL_HARNESS_TEST_APP_PATH+x}
${LOCAL_HARNESS_TEST_APP_PATH-}
LOCAL_HARNESS_TEST_NODE
${LOCAL_HARNESS_TEST_NODE+x}
${LOCAL_HARNESS_TEST_NODE-}
LOCAL_HARNESS_UPDATE_ARCHIVE_TEST_PATH
${LOCAL_HARNESS_UPDATE_ARCHIVE_TEST_PATH+x}
${LOCAL_HARNESS_UPDATE_ARCHIVE_TEST_PATH-}
REQUESTED_BUILD_JOBS
${REQUESTED_BUILD_JOBS+x}
${REQUESTED_BUILD_JOBS-}
REQUESTED_PARALLELISM
${REQUESTED_PARALLELISM+x}
${REQUESTED_PARALLELISM-}
FULMAR_WATCHDOG_BOOTSTRAP_RECORD_V2

# Clear sensitive legacy inputs before the clean exec. The exec also drops
# every other ambient variable; descriptor 9 is the only value-bearing bridge.
unset LOCAL_HARNESS_AUTH_TOKEN LOCAL_HARNESS_SIGNING_KEYCHAIN_PASSWORD

exec /usr/bin/env -i \
  HOME=/private/tmp PATH=/usr/bin:/bin:/usr/sbin:/sbin \
  LANG=en_US.UTF-8 LC_CTYPE=UTF-8 TMPDIR=/private/tmp/ \
  FULMAR_WATCHDOG_BOOTSTRAP_FD_V1=9 \
  /bin/sh -p -c '
    internal=$1
    shift
    run_user=$(/usr/bin/id -un) || exit 126
    run_home=$(/usr/bin/dscl . -read "/Users/$run_user" NFSHomeDirectory) || exit 126
    run_home=${run_home#NFSHomeDirectory: }
    case $run_user in ""|*[!A-Za-z0-9._-]*) exit 126 ;; esac
    case $run_home in /*) ;; *) exit 126 ;; esac
    [ -d "$run_home" ] && [ ! -L "$run_home" ] || exit 126
    USER=$run_user
    LOGNAME=$run_user
    HOME=$run_home
    export USER LOGNAME HOME FULMAR_WATCHDOG_BOOTSTRAP_FD_V1
    export FULMAR_WATCHDOG_CLEAN_LAUNCH_V1=1
    exec /usr/bin/perl "$internal" "$@"
  ' fulmar-watchdog-clean-bootstrap "$SCRIPT_DIR/run-with-watchdog.pl" "$@"
